const config = {
  plugins: ["@trivago/prettier-plugin-sort-imports", "prettier-plugin-tailwindcss"],
  tailwindConfig: "./tailwind.config.ts",
  tabWidth: 2,
  printWidth: 120,
  useTabs: false,
  arrowParens: "always",
  bracketSpacing: true,
  bracketSameLine: false,
  jsxSingleQuote: false,
  quoteProps: "as-needed",
  semi: true,
  singleQuote: false,
  trailingComma: "es5",
  singleAttributePerLine: true,
  importOrder: [
    "^react$",
    "^react-dom$",
    "^@tanstack/(.*)$",
    "^@tanstack/react-router$",
    "^@tanstack/react-table$",
    "^@tanstack/react-form$",
    "^@tanstack/react-start$",
    "^@tanstack/react-router-with-query$",
    "^@tanstack/react-query-devtools$",
    "^@tanstack/react-router-devtools$",
    "^@tanstack/react-query$",
    "<THIRD_PARTY_MODULES>",
    "^@(.*)$",
    "@/components",
    "@/providers",
    "@/hooks",
    "@/lib",
    "@/utils",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderCaseInsensitive: true,
};

export default config;
